apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    app: {{ include "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
stringData:
  database-name: {{ include "postgresql.database" . | quote }}
  database-password: {{ include "postgresql.password" . | quote }}
  database-user: {{ include "postgresql.username" . | quote }}
