apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 5432
    nodePort: 0
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
